# fly.toml app configuration file generated for form-translator-backend on 2025-09-19T14:09:45-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'form-translator-backend'
primary_region = 'ord'

[build]

[deploy]
  release_command = "echo 'Deployment starting...'"

[env]
  DEBUG = 'false'
  FLASK_ENV = 'production'
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '10s'
    method = 'GET'
    path = '/'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1



